import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Download, RefreshCw, Sparkles, AlertTriangle } from "lucide-react";
import { UploadPanel } from "@/components/UploadPanel";
import { ProgressPanel } from "@/components/ProgressPanel";
import { useSharedWallpapers, type Wallpaper } from "@/lib/images";
import { analyzeAll, api } from "@/lib/analyze";
import { buildRows, downloadCsv, type CollectionContent, type CsvRow } from "@/lib/csv";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "BlogText Generator | TextCraft Generator" },
      {
        name: "description",
        content:
          "Turn a folder of wallpapers into a ready-to-publish CSV: collection title, intro, per-image copy, conclusion and SEO metadata generated by AI.",
      },
      { property: "og:title", content: "BlogText Generator" },
      {
        property: "og:description",
        content: "Upload a wallpaper folder and export a key,text CSV with AI-written SEO content.",
      },
    ],
  }),
  component: WallpaperCsvPage,
});

type Phase = "idle" | "analyzing" | "collection" | "done";

function WallpaperCsvPage() {
  const shared = useSharedWallpapers();
  const [images, setImages] = useState<Wallpaper[]>(shared);
  const [phase, setPhase] = useState<Phase>("idle");
  const [progress, setProgress] = useState({ value: 0, current: 0 });
  const [rows, setRows] = useState<CsvRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);

  const busy = phase === "analyzing" || phase === "collection";

  async function generate() {
    if (images.length === 0) return;
    setError(null);
    setWarnings([]);
    setRows(null);
    setPhase("analyzing");
    setProgress({ value: 0, current: 0 });
    try {
      const { analyses, failed } = await analyzeAll(images, (done, current) =>
        setProgress({ value: done, current }),
      );
      setWarnings(failed);
      setPhase("collection");
      const { content } = await api.postJson<{ content: CollectionContent }>(
        "/api/generate-collection",
        { analyses },
      );
      setRows(buildRows(content, images.length));
      setPhase("done");
    } catch (err) {
      setError((err as Error).message);
      setPhase("idle");
    }
  }

  const detail = useMemo(() => {
    if (phase === "analyzing") return `Analyzing image ${progress.current}…`;
    if (phase === "collection") return "Generating collection content and individual descriptions…";
    return undefined;
  }, [phase, progress.current]);

  return (
    <main className="mx-auto max-w-6xl space-y-8 px-5 py-10">
      <header className="space-y-2">
        <h1 className="text-3xl font-extrabold tracking-tight">BlogText Generator</h1>
        <p className="max-w-2xl text-sm text-muted-foreground">
          Drop a folder of wallpapers. Every image is analysed visually, then written up as editorial
          copy and exported as a two-column <code className="rounded bg-secondary px-1">key,text</code> CSV.
        </p>
      </header>

      <UploadPanel images={images} onChange={setImages} disabled={busy} />

      {images.length > 0 && (
        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={generate}
            disabled={busy}
            className="btn-accent inline-flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold transition-opacity hover:opacity-90 disabled:opacity-50"
          >
            <Sparkles className="size-4" />
            {busy ? "Working…" : "Generate CSV"}
          </button>
          {rows && (
            <button
              onClick={generate}
              disabled={busy}
              className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-medium transition-colors hover:bg-secondary disabled:opacity-50"
            >
              <RefreshCw className="size-4" /> Regenerate
            </button>
          )}
        </div>
      )}

      {busy && (
        <ProgressPanel
          label={phase === "analyzing" ? "Analyzing your wallpapers" : "Generating collection content"}
          detail={detail}
          value={phase === "analyzing" ? progress.value : images.length}
          total={images.length}
        />
      )}

      {error && (
        <p className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">
          <AlertTriangle className="mt-0.5 size-4 shrink-0" /> {error}
        </p>
      )}

      {warnings.length > 0 && (
        <div className="rounded-lg border border-border bg-secondary px-4 py-3 text-sm text-muted-foreground">
          <p className="mb-1 font-medium text-foreground">Some images could not be analysed:</p>
          <ul className="list-inside list-disc">
            {warnings.map((w) => (
              <li key={w}>{w}</li>
            ))}
          </ul>
        </div>
      )}

      {rows && (
        <section className="surface-card overflow-hidden">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4">
            <div>
              <h2 className="font-semibold">Your CSV is ready</h2>
              <p className="text-sm text-muted-foreground">
                {rows.length} rows — image_1 to image_{images.length}. Text is editable before download.
              </p>
            </div>
            <button
              onClick={() => downloadCsv(rows)}
              className="btn-accent inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-opacity hover:opacity-90"
            >
              <Download className="size-4" /> Download CSV
            </button>
          </div>
          <div className="max-h-[560px] overflow-auto">
            <table className="w-full border-collapse text-sm">
              <thead className="sticky top-0 bg-secondary text-left">
                <tr>
                  <th className="w-44 px-5 py-2.5 font-semibold">key</th>
                  <th className="px-5 py-2.5 font-semibold">text</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row, i) => (
                  <tr key={row.key} className="border-t border-border align-top">
                    <td className="px-5 py-3 font-mono text-xs text-muted-foreground">{row.key}</td>
                    <td className="px-3 py-2">
                      <textarea
                        value={row.text}
                        rows={Math.min(6, Math.max(2, Math.ceil(row.text.length / 90)))}
                        onChange={(e) => {
                          const next = [...rows];
                          next[i] = { key: row.key, text: e.target.value };
                          setRows(next);
                        }}
                        className="w-full resize-y rounded-md border border-transparent bg-transparent px-2 py-1 leading-relaxed outline-none transition-colors focus:border-border focus:bg-secondary"
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}
    </main>
  );
}
